import csv
import matplotlib.pyplot as plt
import os

# --- Configuration ---
CSV_FILE = "results/01_batching_cliff/batching_metrics_llama3_1_8b.csv"
OUTPUT_IMAGE = "results/01_batching_cliff/batching_cliff_llama3_1_8b.png"

def generate_dual_axis_plot(csv_path, output_path):
    print(f"📊 Reading data from {csv_path}...")
    
    batch_sizes = []
    latencies = []
    throughputs = []

    # Read the CSV generated by the benchmark
    try:
        with open(csv_path, 'r') as file:
            reader = csv.DictReader(file)
            for row in reader:
                # We store batch size as a string so the graph spaces the powers of 2 evenly
                batch_sizes.append(str(row["batch_size"]))
                latencies.append(float(row["latency_ms"]))
                throughputs.append(float(row["throughput_tok_sec"]))
    except FileNotFoundError:
        print(f"❌ Error: Could not find {csv_path}. Did you run the benchmark first?")
        return

    # Initialize the plot
    fig, ax1 = plt.subplots(figsize=(10, 6))

    # --- Left Y-Axis: Latency ---
    color1 = 'tab:red'
    ax1.set_xlabel('Batch Size', fontweight='bold')
    ax1.set_ylabel('Latency (ms)', color=color1, fontweight='bold')
    # Plot latency as a line with circular markers
    line1 = ax1.plot(batch_sizes, latencies, color=color1, marker='o', linewidth=2, label='Latency (ms)')
    ax1.tick_params(axis='y', labelcolor=color1)
    ax1.grid(True, linestyle='--', alpha=0.6)

    # --- Right Y-Axis: Throughput ---
    ax2 = ax1.twinx()  # Create a second y-axis sharing the same x-axis
    color2 = 'tab:blue'
    ax2.set_ylabel('Throughput (tokens/sec)', color=color2, fontweight='bold')
    # Plot throughput as a line with square markers
    line2 = ax2.plot(batch_sizes, throughputs, color=color2, marker='s', linewidth=2, label='Throughput (tok/s)')
    ax2.tick_params(axis='y', labelcolor=color2)

    # --- Formatting ---
    # Combine legends from both axes
    lines = line1 + line2
    labels = [l.get_label() for l in lines]
    ax1.legend(lines, labels, loc='upper left')

    plt.title('The Batching Cliff: RTX 4090 vs Llama-3.1-8B-Instruct', fontsize=14, fontweight='bold')
    fig.tight_layout()  # Ensure labels don't get cut off

    # Save the file
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    plt.savefig(output_path, dpi=300)
    print(f"✅ Graph successfully saved to {output_path}")

if __name__ == "__main__":
    generate_dual_axis_plot(CSV_FILE, OUTPUT_IMAGE)